version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4005:4005"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        consistency: cached
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/transport_app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transport_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
